/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.memory.views;

import com.memory.control.SignUpController;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Caiquekola
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        nickname.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    cadastrar();
                }
            }
        });

        email.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    cadastrar();
                }
            }
        });
        senha1.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    cadastrar();
                }
            }
        });
        senha2.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    cadastrar();
                }
            }
        });
    }

    private void cadastrar() {
        //Testar todos os campos preenchidos
        if (nickname.getText().isEmpty() || email.getText().isEmpty() || senha1.getPassword().length == 0 || senha2.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Preencha todos os campos", JOptionPane.HEIGHT);
        } //Senhas conferem?
        else if (!java.util.Arrays.equals(senha1.getPassword(), senha2.getPassword())) {
            JOptionPane.showMessageDialog(this, "ERRO! Senha não conferem!", "Erro de Senhas!", JOptionPane.ERROR_MESSAGE);
        } else {

            try {
                SignUpController signUp = new SignUpController();
                
                int emailCadastrado = signUp.emailUtilizado(this);
                int nicknameCadastrado = signUp.nicknameUtilizado(this);
                
                if(emailCadastrado == 0){
                    JOptionPane.showMessageDialog(this, "ERRO! Email já cadastrado, tente novamente!", "Erro de Login!", JOptionPane.YES_OPTION);
                    return;
                }
                
                if(nicknameCadastrado == 0){
                    JOptionPane.showMessageDialog(this, "ERRO! Nickname já cadastrado, tente novamente!", "Erro de Login!", JOptionPane.YES_OPTION);
                    return;
                }
                
                int opcao = signUp.signUpUsuario(this);
                
                switch (opcao) {
                    case -1:
                        JOptionPane.showMessageDialog(this, "ERRO! Algum erro ocorreu, tente novamente!", "Erro de Login!", JOptionPane.YES_OPTION);
                        break;
                    default:

                        this.dispose();
                        Login login = new Login();
                        login.setVisible(true);
                        break;
                }
            }catch (SQLException sql) {
                // Tratamento de exceção
                System.out.println(sql.getCause());
            }

        }

        //Testar se já existe usuário...
    }

    public JTextField getEmail() {
        return email;
    }

    public JTextField getNickname() {
        return nickname;
    }

    public JPasswordField getSenha1() {
        return senha1;
    }

    public JPasswordField getSenha2() {
        return senha2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nickname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        senha1 = new javax.swing.JPasswordField();
        senha2 = new javax.swing.JPasswordField();
        wpp = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        cadastrar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nickname.setToolTipText("Nickname");
        nickname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicknameActionPerformed(evt);
            }
        });
        getContentPane().add(nickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 320, 30));

        email.setToolTipText("Email");
        email.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 320, 40));

        senha1.setToolTipText("Digite sua senha aqui");
        getContentPane().add(senha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 320, 30));

        senha2.setToolTipText("Repita sua senha aqui");
        senha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senha2ActionPerformed(evt);
            }
        });
        getContentPane().add(senha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 320, 30));

        wpp.setIcon(new javax.swing.ImageIcon("D:\\Projetos\\TrabalhoBancoDeDadosVersaoPC\\ultimaVersao\\TrabalhoBancoDeDados\\Memory\\src\\main\\java\\com\\memory\\resources\\Cadastro.png")); // NOI18N
        getContentPane().add(wpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        login.setText("Login");
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 130, 30));

        cadastrar.setText("Cadastrar");
        cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 170, 40));

        voltar.setText("Voltar");
        voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                voltarMouseEntered(evt);
            }
        });
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 130, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicknameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void senha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senha2ActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        // TODO add your handling code here:

        cadastrar();
    }//GEN-LAST:event_cadastrarActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:

        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginActionPerformed

    private void voltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_voltarMouseEntered

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MenuInicial tl = new MenuInicial();
        tl.setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar;
    private javax.swing.JTextField email;
    private javax.swing.JButton login;
    private javax.swing.JTextField nickname;
    private javax.swing.JPasswordField senha1;
    private javax.swing.JPasswordField senha2;
    private javax.swing.JButton voltar;
    private javax.swing.JLabel wpp;
    // End of variables declaration//GEN-END:variables
}
