/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.memory.views;

import com.memory.bean.Jogador;
import com.memory.bean.Jogo;
import com.memory.dao.JogadorDAO;

/**
 *
 * @author Caique
 */
public class GameOverSolo extends javax.swing.JFrame {

    /**
     * Creates new form GameOver
     */
    private Jogador jogador;
    private int acertos;
    private int recs = 0;
    private int nivel = 0;
    private Jogo jogo;

    public GameOverSolo(Jogador jogador, Jogo jogo) {
        initComponents();
        this.jogador = jogador;
        this.acertos = jogo.getPontos();
        this.nivel = jogo.getNivel();
        this.jogo = jogo;

        alterarRecorde();
        if (jogo.getPontos()>=25) {
            conquista();
        }
    }

    public GameOverSolo() {
        initComponents();
    }

    private void conquista() {
        JogadorDAO jogadorD = new JogadorDAO();
        jogadorD.verificarEAdicionarConquista(jogador, 3);
    }

    private void alterarRecorde() {

        ultimoPontos.setText(String.valueOf(acertos));
        //Busca recorde do jogador
        JogadorDAO jogadorDao = new JogadorDAO();

        int recordeModoDeJogo = -1;

        this.ultimoPontos.setText(String.valueOf(jogo.getPontos()));
        //Definicao text do modo
        String nivelText = "";

        if (nivel == 0) {
            nivelText = "FÁCIL";

        } else if (nivel == 1) {
            nivelText = "MÉDIO";
        } else if (nivel == 2) {
            nivelText = "DÍFICIL";
        } else if (nivel == 3) {
            nivelText = "INFINITO";

        }
        recordeModoDeJogo = jogadorDao.recordeJogadorDificuldade(jogador, nivel);
        recordePontos.setText(String.valueOf(recordeModoDeJogo));

        this.nivelJ.setText(nivelText);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recordePontos = new javax.swing.JLabel();
        nivelJ = new javax.swing.JLabel();
        ultimoPontos = new javax.swing.JLabel();
        wpp = new javax.swing.JLabel();
        jogarNovamente = new javax.swing.JButton();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recordePontos.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        recordePontos.setForeground(new java.awt.Color(51, 51, 255));
        recordePontos.setText("23");
        getContentPane().add(recordePontos, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 120, 160));

        nivelJ.setBackground(new java.awt.Color(153, 51, 255));
        nivelJ.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        nivelJ.setForeground(new java.awt.Color(255, 0, 51));
        nivelJ.setText("DIFICIL");
        getContentPane().add(nivelJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, -1, -1));

        ultimoPontos.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        ultimoPontos.setForeground(new java.awt.Color(204, 0, 0));
        ultimoPontos.setText("23");
        getContentPane().add(ultimoPontos, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 100, 160));

        wpp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/memory/resources/GOSolo.png"))); // NOI18N
        getContentPane().add(wpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jogarNovamente.setText("jButton1");
        jogarNovamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogarNovamenteActionPerformed(evt);
            }
        });
        getContentPane().add(jogarNovamente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 180, 50));

        voltar.setText("jButton1");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, 130, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jogarNovamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogarNovamenteActionPerformed
        // TODO add your handling code here:
        Solo solo = new Solo(jogador, nivel);
        solo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jogarNovamenteActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(jogador);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameOverSolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameOverSolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameOverSolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameOverSolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameOverSolo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jogarNovamente;
    private javax.swing.JLabel nivelJ;
    private javax.swing.JLabel recordePontos;
    private javax.swing.JLabel ultimoPontos;
    private javax.swing.JButton voltar;
    private javax.swing.JLabel wpp;
    // End of variables declaration//GEN-END:variables
}
