
package com.memory.views;

import com.memory.bean.Jogador;

/**
 *
 * @author Caiquekola
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private Jogador usuario;
    
    public Menu(Jogador usuario) {
        initComponents();
        this.usuario = usuario;
        setarNome();
        
    }
    public Menu() {
        initComponents();
        this.usuario = null;
    }
    
    private void setarNome(){
        if(!usuario.equals(null)){
                   nickname.setText(usuario.getNickname());
 
        }
        
        
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nickname = new javax.swing.JLabel();
        wpp = new javax.swing.JLabel();
        solo = new javax.swing.JButton();
        dupla = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        perfilbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nickname.setBackground(new java.awt.Color(255, 255, 255));
        nickname.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        nickname.setForeground(new java.awt.Color(255, 255, 255));
        nickname.setText("USUÁRIO");
        getContentPane().add(nickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 160, 50));

        wpp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/memory/resources/Menu.png"))); // NOI18N
        getContentPane().add(wpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        solo.setText("solo");
        solo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soloActionPerformed(evt);
            }
        });
        getContentPane().add(solo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 170, 50));

        dupla.setText("dupla");
        dupla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duplaActionPerformed(evt);
            }
        });
        getContentPane().add(dupla, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 170, 50));

        voltar.setText("voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, 160, 40));

        perfilbutton.setText("perfil");
        perfilbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(perfilbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 170, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void soloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soloActionPerformed
        // TODO add your handling code here:
        MenuDificuldade solo = new MenuDificuldade(usuario);
        this.dispose();
        solo.setVisible(true);
    }//GEN-LAST:event_soloActionPerformed

    private void duplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duplaActionPerformed
        // TODO add your handling code here:
        Dupla d = new Dupla(usuario,0,0);
        dupla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_duplaActionPerformed

    private void perfilbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilbuttonActionPerformed
        // TODO add your handling code here:
        Perfil perfil = new Perfil(usuario);
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_perfilbuttonActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dupla;
    private javax.swing.JLabel nickname;
    private javax.swing.JButton perfilbutton;
    private javax.swing.JButton solo;
    private javax.swing.JButton voltar;
    private javax.swing.JLabel wpp;
    // End of variables declaration//GEN-END:variables
}
