package com.memory.views;




import com.memory.bean.Jogador;
import com.memory.views.Menu;
import com.memory.views.Solo;

/**
 *
 * @author Caiquekola
 */
public class MenuDificuldade extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private Jogador usuario;
    
    public MenuDificuldade(Jogador usuario) {
        initComponents();
        this.usuario = usuario;
        setarNome();
        
    }
    public MenuDificuldade() {
        initComponents();
        this.usuario = null;
    }
    
    private void setarNome(){
        if(!usuario.equals(null)){
                   nickname.setText(usuario.getNickname());
 
        }
        
        
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nickname = new javax.swing.JLabel();
        wpp = new javax.swing.JLabel();
        facil = new javax.swing.JButton();
        medio = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        dificil = new javax.swing.JButton();
        infinito = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nickname.setBackground(new java.awt.Color(255, 255, 255));
        nickname.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        nickname.setForeground(new java.awt.Color(255, 255, 255));
        nickname.setText("USUÁRIO");
        getContentPane().add(nickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 160, 50));

        wpp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/memory/resources/Dificuldade.png"))); // NOI18N
        getContentPane().add(wpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        facil.setText("facil");
        facil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facilActionPerformed(evt);
            }
        });
        getContentPane().add(facil, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 170, 50));

        medio.setText("medio");
        medio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medioActionPerformed(evt);
            }
        });
        getContentPane().add(medio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 170, 40));

        voltar.setText("voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 160, 40));

        dificil.setText("dificil");
        dificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dificilActionPerformed(evt);
            }
        });
        getContentPane().add(dificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 170, 50));

        infinito.setText("infinito");
        infinito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infinitoActionPerformed(evt);
            }
        });
        getContentPane().add(infinito, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 170, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Menu menu = new Menu(usuario);
        menu.setVisible(true);
        
    }//GEN-LAST:event_voltarActionPerformed

    private void facilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facilActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Solo solo = new Solo(usuario,0);
        solo.setVisible(true);
    }//GEN-LAST:event_facilActionPerformed

    private void medioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medioActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Solo solo = new Solo(usuario,1);
        solo.setVisible(true);
    }//GEN-LAST:event_medioActionPerformed

    private void dificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dificilActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        Solo solo = new Solo(usuario,2);
        solo.setVisible(true);
                      
        
    }//GEN-LAST:event_dificilActionPerformed

    private void infinitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infinitoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Solo solo = new Solo(usuario,3);
        solo.setVisible(true);
    }//GEN-LAST:event_infinitoActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDificuldade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDificuldade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDificuldade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDificuldade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDificuldade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dificil;
    private javax.swing.JButton facil;
    private javax.swing.JButton infinito;
    private javax.swing.JButton medio;
    private javax.swing.JLabel nickname;
    private javax.swing.JButton voltar;
    private javax.swing.JLabel wpp;
    // End of variables declaration//GEN-END:variables
}
