/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.memory.views;

import com.memory.bean.Jogador;
import com.memory.dao.ConquistaDAO;
import com.memory.dao.JogadorDAO;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Caiquekola
 */
public class Perfil extends javax.swing.JFrame {

    /**
     * Creates new form Perfil
     */
    Jogador jogador;
    private Map<Integer, JLabel> conquistasLabels;
    
    
    
    public Perfil() {
        initComponents();
    }

    public Perfil(Jogador jogador) {
        initComponents();
        this.jogador = jogador;

        alterarRecorde();
        alterarRank();
        alterarNickname();
        alterarEmail();
        
        
        conquistas();
        
        conquistaHacker();
    }
    private void inicializarConquistasLabels() {
        conquistasLabels = new HashMap<>();
        conquistasLabels.put(5, DuoPro);
        conquistasLabels.put(6, Hacker);
        conquistasLabels.put(2, genio);
        conquistasLabels.put(1, memoriaDeOuro);
        conquistasLabels.put(3, memoriaElefante);
        conquistasLabels.put(4, memoriaFotografica);
    }

    // Esconde todas as labels
    private void esconderTodas() {
        for (JLabel label : conquistasLabels.values()) {
            label.setVisible(false);
        }
    }

    // Atualiza as labels com base nas conquistas do jogador
    public void conquistas() {
        inicializarConquistasLabels();
        esconderTodas();
        ConquistaDAO conquistaDao = new ConquistaDAO();
        for (Map.Entry<Integer, JLabel> entry : conquistasLabels.entrySet()) {
            int conquistaId = entry.getKey();
            JLabel label = entry.getValue();
            if (conquistaDao.possuiConquista(jogador.getId(), conquistaId)) {
                label.setVisible(true);
            }
        }
    }
    
    
    
    
    public void conquistaHacker(){
        ConquistaDAO conquistaDAO = new ConquistaDAO();
        conquistaDAO.verificarEAdicionarConquistaHacker(jogador.getId());
    }
    public void alterarNickname() {
        this.nickname.setText(jogador.getNickname());
    }
    
    public void alterarEmail(){
        this.emailJ.setText(jogador.getEmail());
    }
    
    public void alterarRecorde() {
        JogadorDAO recordeJogador = new JogadorDAO();
        int recordePontos = recordeJogador.recordeJogadorDificuldade(jogador, 3);
        this.recorde.setText(String.valueOf(recordePontos));
    }

    public void alterarRank() {
        JogadorDAO rankJogador = new JogadorDAO();
        int rankPosicao = rankJogador.posicaoRank(jogador);
        this.rank.setText(String.valueOf(rankPosicao));
    }

    public void deletarConta() {
        JogadorDAO deletarConta = new JogadorDAO();
        int response = JOptionPane.showConfirmDialog(null,
                "Você realmente deseja excluir sua conta?",
                "Confirmação de Exclusão",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            // Código para excluir a conta
            System.out.println("Conta excluída");
            deletarConta.deletarConta(jogador);
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
        } else {
            System.out.println("Exclusão cancelada");
        }
    }

    public void resetarScore() {
        JogadorDAO resetarScore = new JogadorDAO();
        int response = JOptionPane.showConfirmDialog(null,
                "Você realmente deseja resetar sua conta?",
                "Confirmação de Reset",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            // Código para excluir a conta
            System.out.println("Conta resetada");
            resetarScore.resetScore(jogador);
        } else {
            System.out.println("Reset cancelado");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailJ = new javax.swing.JLabel();
        nickname = new javax.swing.JLabel();
        recorde = new javax.swing.JLabel();
        memoriaDeOuro = new javax.swing.JLabel();
        genio = new javax.swing.JLabel();
        memoriaElefante = new javax.swing.JLabel();
        DuoPro = new javax.swing.JLabel();
        Hacker = new javax.swing.JLabel();
        memoriaFotografica = new javax.swing.JLabel();
        rank = new javax.swing.JLabel();
        wpp = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        ExplicacaoConquistas = new javax.swing.JButton();
        resetarScore = new javax.swing.JButton();
        deletarConta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailJ.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        emailJ.setForeground(new java.awt.Color(153, 102, 0));
        emailJ.setText("test@test.com.br");
        getContentPane().add(emailJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 260, 30));

        nickname.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        nickname.setForeground(new java.awt.Color(153, 102, 0));
        nickname.setText("nickname");
        getContentPane().add(nickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 150, 30));

        recorde.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        recorde.setForeground(new java.awt.Color(153, 102, 0));
        recorde.setText("23");
        getContentPane().add(recorde, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 70, 30));

        memoriaDeOuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/memory/resources/Conquistas/miniaturas/MemoriadeOuro1.png"))); // NOI18N
        memoriaDeOuro.setMinimumSize(new java.awt.Dimension(200, 100));
        getContentPane().add(memoriaDeOuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 80, 70));

        genio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/memory/resources/Conquistas/miniaturas/Genio1.png"))); // NOI18N
        getContentPane().add(genio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, -1));

        memoriaElefante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/memory/resources/Conquistas/miniaturas/MemoriaElefante1.png"))); // NOI18N
        getContentPane().add(memoriaElefante, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 139, 80, 70));

        DuoPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/memory/resources/Conquistas/miniaturas/DuoPro1.png"))); // NOI18N
        getContentPane().add(DuoPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 90, 80));

        Hacker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/memory/resources/Conquistas/miniaturas/Hacker1.png"))); // NOI18N
        getContentPane().add(Hacker, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, -1, -1));

        memoriaFotografica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/memory/resources/Conquistas/miniaturas/MemoriaFotografica1.png"))); // NOI18N
        getContentPane().add(memoriaFotografica, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        rank.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        rank.setForeground(new java.awt.Color(153, 102, 0));
        rank.setText("23");
        getContentPane().add(rank, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 70, 30));

        wpp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/memory/resources/Conquistas.png"))); // NOI18N
        getContentPane().add(wpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        voltar.setText("voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 130, 40));

        ExplicacaoConquistas.setText("Conquistas");
        ExplicacaoConquistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExplicacaoConquistasActionPerformed(evt);
            }
        });
        getContentPane().add(ExplicacaoConquistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 50, 40));

        resetarScore.setText("resetarScore");
        resetarScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetarScoreActionPerformed(evt);
            }
        });
        getContentPane().add(resetarScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 210, 60));

        deletarConta.setText("resetarScore");
        deletarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarContaActionPerformed(evt);
            }
        });
        getContentPane().add(deletarConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 210, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deletarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarContaActionPerformed
        // TODO add your handling code here:
        deletarConta();
    }//GEN-LAST:event_deletarContaActionPerformed

    private void resetarScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetarScoreActionPerformed
        // TODO add your handling code here:
        resetarScore();
    }//GEN-LAST:event_resetarScoreActionPerformed

    private void ExplicacaoConquistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExplicacaoConquistasActionPerformed
        // TODO add your handling code here:
        ExplicacaoConquistas ec = new ExplicacaoConquistas(jogador);
        ec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExplicacaoConquistasActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(jogador);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DuoPro;
    private javax.swing.JButton ExplicacaoConquistas;
    private javax.swing.JLabel Hacker;
    private javax.swing.JButton deletarConta;
    private javax.swing.JLabel emailJ;
    private javax.swing.JLabel genio;
    private javax.swing.JLabel memoriaDeOuro;
    private javax.swing.JLabel memoriaElefante;
    private javax.swing.JLabel memoriaFotografica;
    private javax.swing.JLabel nickname;
    private javax.swing.JLabel rank;
    private javax.swing.JLabel recorde;
    private javax.swing.JButton resetarScore;
    private javax.swing.JButton voltar;
    private javax.swing.JLabel wpp;
    // End of variables declaration//GEN-END:variables
}
