/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.memory.views;

import com.memory.dao.JogoDAO;

/**
 *
 * @author Caiquekola
 */
public class Ranking extends javax.swing.JFrame {

    /**
     * Creates new form Ranking
     */
    public Ranking() {
        initComponents();
        alterarValores();
    }

    private void alterarValores() {
        JogoDAO jogoDAO = new JogoDAO();

        // Atualiza os valores dos JLabels
        int totalPartidas = jogoDAO.getTotalPartidasJogadas();
        String usuarioComMaisPartidas = jogoDAO.getUsuarioComMaisPartidas();
        int maiorPontuacao = jogoDAO.getMaiorPontuacaoInfinito();
        double mediaPontuacao = jogoDAO.getMediaPontuacaoModoInfinito();

        partidasJogadasAteOMomento.setText(String.valueOf(totalPartidas));
        UsuarioComMaisPartidasJogadas.setText(usuarioComMaisPartidas);
        MaiorPontuacaoInfinito.setText(String.valueOf(maiorPontuacao));
        MediaPontuacaoModoInfinito.setText(String.format("%.0f", mediaPontuacao));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        partidasJogadasAteOMomento = new javax.swing.JLabel();
        UsuarioComMaisPartidasJogadas = new javax.swing.JLabel();
        MaiorPontuacaoInfinito = new javax.swing.JLabel();
        MediaPontuacaoModoInfinito = new javax.swing.JLabel();
        wpp = new javax.swing.JLabel();
        top10 = new javax.swing.JButton();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        partidasJogadasAteOMomento.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        partidasJogadasAteOMomento.setForeground(new java.awt.Color(51, 51, 51));
        partidasJogadasAteOMomento.setText("233");
        getContentPane().add(partidasJogadasAteOMomento, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, -1, -1));

        UsuarioComMaisPartidasJogadas.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        UsuarioComMaisPartidasJogadas.setForeground(new java.awt.Color(51, 51, 51));
        UsuarioComMaisPartidasJogadas.setText("Desconhecido");
        getContentPane().add(UsuarioComMaisPartidasJogadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 230, -1));

        MaiorPontuacaoInfinito.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        MaiorPontuacaoInfinito.setForeground(new java.awt.Color(51, 51, 51));
        MaiorPontuacaoInfinito.setText("233");
        getContentPane().add(MaiorPontuacaoInfinito, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, -1, 30));

        MediaPontuacaoModoInfinito.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        MediaPontuacaoModoInfinito.setForeground(new java.awt.Color(51, 51, 51));
        MediaPontuacaoModoInfinito.setText("233");
        getContentPane().add(MediaPontuacaoModoInfinito, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, -1, 30));

        wpp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/memory/resources/Relatorios.png"))); // NOI18N
        getContentPane().add(wpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        top10.setText("jButton1");
        top10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                top10ActionPerformed(evt);
            }
        });
        getContentPane().add(top10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 210, 60));

        voltar.setText("jButton1");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 523, 130, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        MenuInicial m = new MenuInicial();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void top10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_top10ActionPerformed
        // TODO add your handling code here:
        Top10 t = new Top10();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_top10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ranking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MaiorPontuacaoInfinito;
    private javax.swing.JLabel MediaPontuacaoModoInfinito;
    private javax.swing.JLabel UsuarioComMaisPartidasJogadas;
    private javax.swing.JLabel partidasJogadasAteOMomento;
    private javax.swing.JButton top10;
    private javax.swing.JButton voltar;
    private javax.swing.JLabel wpp;
    // End of variables declaration//GEN-END:variables
}
