/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.memory.views;

import com.memory.connection.ConnectionFactory;
import javax.swing.JLabel;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author Caiquekola
 */
public class Top10 extends javax.swing.JFrame {

    /**
     * Creates new form Ranking
     */
    public Top10() {
        initComponents();
        alterarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome10 = new javax.swing.JLabel();
        nome8 = new javax.swing.JLabel();
        nome9 = new javax.swing.JLabel();
        nome6 = new javax.swing.JLabel();
        nome7 = new javax.swing.JLabel();
        nome5 = new javax.swing.JLabel();
        nome4 = new javax.swing.JLabel();
        nome3 = new javax.swing.JLabel();
        nome1 = new javax.swing.JLabel();
        nome2 = new javax.swing.JLabel();
        pt4 = new javax.swing.JLabel();
        pt5 = new javax.swing.JLabel();
        pt7 = new javax.swing.JLabel();
        pt6 = new javax.swing.JLabel();
        pt10 = new javax.swing.JLabel();
        pt9 = new javax.swing.JLabel();
        pt8 = new javax.swing.JLabel();
        pt3 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        pt2 = new javax.swing.JLabel();
        wpp = new javax.swing.JLabel();
        top10 = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        partidas2 = new javax.swing.JLabel();
        usuarioPartidas2 = new javax.swing.JLabel();
        media2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nome10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        nome10.setForeground(new java.awt.Color(0, 0, 0));
        nome10.setText("CLEITON");
        getContentPane().add(nome10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, 190, 40));

        nome8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        nome8.setForeground(new java.awt.Color(0, 0, 0));
        nome8.setText("CLEITON");
        getContentPane().add(nome8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 190, 40));

        nome9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        nome9.setForeground(new java.awt.Color(0, 0, 0));
        nome9.setText("CLEITON");
        getContentPane().add(nome9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 190, 40));

        nome6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        nome6.setForeground(new java.awt.Color(0, 0, 0));
        nome6.setText("CLEITON");
        getContentPane().add(nome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 190, 40));

        nome7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        nome7.setForeground(new java.awt.Color(0, 0, 0));
        nome7.setText("CLEITON");
        getContentPane().add(nome7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 190, 40));

        nome5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        nome5.setForeground(new java.awt.Color(0, 0, 0));
        nome5.setText("CLEITON");
        getContentPane().add(nome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 190, 40));

        nome4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        nome4.setForeground(new java.awt.Color(0, 0, 0));
        nome4.setText("CLEITON");
        getContentPane().add(nome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 190, 40));

        nome3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        nome3.setForeground(new java.awt.Color(153, 153, 153));
        nome3.setText("CLEITON");
        getContentPane().add(nome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 190, 40));

        nome1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        nome1.setForeground(new java.awt.Color(255, 255, 255));
        nome1.setText("CLEITON");
        getContentPane().add(nome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 160, 40));

        nome2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        nome2.setForeground(new java.awt.Color(255, 255, 255));
        nome2.setText("CLEITON");
        getContentPane().add(nome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 190, 40));

        pt4.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        pt4.setForeground(new java.awt.Color(51, 51, 51));
        pt4.setText("233");
        getContentPane().add(pt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, -1, -1));

        pt5.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        pt5.setForeground(new java.awt.Color(51, 51, 51));
        pt5.setText("233");
        getContentPane().add(pt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, -1, -1));

        pt7.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        pt7.setForeground(new java.awt.Color(51, 51, 51));
        pt7.setText("233");
        getContentPane().add(pt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, -1, -1));

        pt6.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        pt6.setForeground(new java.awt.Color(51, 51, 51));
        pt6.setText("233");
        getContentPane().add(pt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, -1, -1));

        pt10.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        pt10.setForeground(new java.awt.Color(51, 51, 51));
        pt10.setText("233");
        getContentPane().add(pt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 470, -1, -1));

        pt9.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        pt9.setForeground(new java.awt.Color(51, 51, 51));
        pt9.setText("233");
        getContentPane().add(pt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, -1, -1));

        pt8.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        pt8.setForeground(new java.awt.Color(51, 51, 51));
        pt8.setText("233");
        getContentPane().add(pt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, -1, -1));

        pt3.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        pt3.setForeground(new java.awt.Color(51, 51, 51));
        pt3.setText("233");
        getContentPane().add(pt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 80, 60));

        p1.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        p1.setForeground(new java.awt.Color(51, 51, 51));
        p1.setText("233");
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        pt2.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        pt2.setForeground(new java.awt.Color(51, 51, 51));
        pt2.setText("233");
        getContentPane().add(pt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        wpp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/memory/resources/Top10Jogadores.png"))); // NOI18N
        getContentPane().add(wpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        top10.setText("jButton1");
        top10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                top10ActionPerformed(evt);
            }
        });
        getContentPane().add(top10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 210, 60));

        voltar.setText("jButton1");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 523, 130, 40));

        partidas2.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        partidas2.setForeground(new java.awt.Color(51, 51, 51));
        partidas2.setText("233");
        getContentPane().add(partidas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));

        usuarioPartidas2.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        usuarioPartidas2.setForeground(new java.awt.Color(51, 51, 51));
        usuarioPartidas2.setText("233");
        getContentPane().add(usuarioPartidas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        media2.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        media2.setForeground(new java.awt.Color(51, 51, 51));
        media2.setText("233");
        getContentPane().add(media2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        MenuInicial m = new MenuInicial();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void top10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_top10ActionPerformed
        // TODO add your handling code here:
        Top10 t = new Top10();
        t.setVisible(true);
        this.dispose();
        alterarTabela();
        
    }//GEN-LAST:event_top10ActionPerformed
    private void alterarTabela() {
        try (Connection con = ConnectionFactory.getConnection()) {
            // Preparar e executar a consulta
            String sql = "SELECT jogador.nickname, MAX(jogo.pontos) AS maior_pontos "
                    + "FROM jogador JOIN jogo ON jogador.id = jogo.id_player1 "
                    + "GROUP BY jogador.nickname ORDER BY maior_pontos DESC LIMIT 10";
            try (PreparedStatement stmt = con.prepareStatement(sql)) {
                ResultSet rs = stmt.executeQuery();

                // Inicializar variáveis para armazenar os dados
                JLabel[] nomes = {nome1, nome2, nome3, nome4, nome5, nome6, nome7, nome8, nome9, nome10};
                JLabel[] pontuacoes = {p1, pt2, pt3, pt4, pt5, pt6, pt7, pt8, pt9, pt10};

                // Atualizar os labels com os dados
                int i = 0;
                while (rs.next() && i < 10) {
                    String nome = rs.getString("nickname");
                    int pontos = rs.getInt("maior_pontos");

                    // Atualizar o nome e a pontuação no label correspondente
                    nomes[i].setText(nome);
                    pontuacoes[i].setText(String.valueOf(pontos));
                    i++;
                }

                // Preencher os campos restantes com dados padrão, se necessário
                for (int j = i; j < 10; j++) {
                    nomes[j].setText("N/A");
                    pontuacoes[j].setText("0");
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            // Tratar exceções, como exibir uma mensagem de erro
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Top10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Top10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Top10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Top10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Top10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel media2;
    private javax.swing.JLabel nome1;
    private javax.swing.JLabel nome10;
    private javax.swing.JLabel nome2;
    private javax.swing.JLabel nome3;
    private javax.swing.JLabel nome4;
    private javax.swing.JLabel nome5;
    private javax.swing.JLabel nome6;
    private javax.swing.JLabel nome7;
    private javax.swing.JLabel nome8;
    private javax.swing.JLabel nome9;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel partidas2;
    private javax.swing.JLabel pt10;
    private javax.swing.JLabel pt2;
    private javax.swing.JLabel pt3;
    private javax.swing.JLabel pt4;
    private javax.swing.JLabel pt5;
    private javax.swing.JLabel pt6;
    private javax.swing.JLabel pt7;
    private javax.swing.JLabel pt8;
    private javax.swing.JLabel pt9;
    private javax.swing.JButton top10;
    private javax.swing.JLabel usuarioPartidas2;
    private javax.swing.JButton voltar;
    private javax.swing.JLabel wpp;
    // End of variables declaration//GEN-END:variables
}
