package com.memory.views;

import com.memory.bean.Jogador;
import com.memory.bean.Jogo;
import com.memory.dao.JogadorDAO;

/**
 *
 * @author Caiquekola
 */
public class VitoriaSolo extends javax.swing.JFrame {

    /**
     * Creates new form VitoriaSolo
     */
    
    private int acertos,nivel;
    private Jogador jogador;
    private Jogo jogo;
    
    public VitoriaSolo() {
        initComponents();
    }
    public VitoriaSolo(Jogador jogador, Jogo jogo) {
        initComponents();
        this.jogador = jogador;
        this.acertos = jogo.getPontos();
        this.nivel = jogo.getNivel();
        this.jogo = jogo;
        
        
        
        alterarInterface();
        conquistas();
        
    }
    public void conquistas(){
        JogadorDAO jogadorDao = new JogadorDAO();
        //Adição de conquista do jogador, nivel designa a conquista
        jogadorDao.verificarEAdicionarConquista(jogador, nivel+1);
        
    }
    public void alterarInterface(){
        
        //Busca recorde do jogador
        JogadorDAO jogadorDao = new JogadorDAO();
        
        
        
        int recordeModoDeJogo = -1; 
        
        
        
        this.ultimoPontos.setText(String.valueOf(jogo.getPontos()));
        //Definicao text do modo
        String nivelText = "";
        
        if(nivel == 0){
            nivelText = "FÁCIL";
            
        }else if(nivel ==1){
            nivelText = "MÉDIO";
        }else if(nivel == 2){
            nivelText = "DÍFICIL";
        }else if(nivel == 3){
            nivelText = "INFINITO";
            
        }
        recordeModoDeJogo = jogadorDao.recordeJogadorDificuldade(jogador,nivel);
        recordePontos.setText(String.valueOf(recordeModoDeJogo));
        
        this.nivelJ.setText(nivelText);
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recordePontos = new javax.swing.JLabel();
        nivelJ = new javax.swing.JLabel();
        ultimoPontos = new javax.swing.JLabel();
        wpp = new javax.swing.JLabel();
        Menu = new javax.swing.JButton();
        jogarNovamente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recordePontos.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        recordePontos.setForeground(new java.awt.Color(51, 51, 255));
        recordePontos.setText("23");
        getContentPane().add(recordePontos, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 120, 160));

        nivelJ.setBackground(new java.awt.Color(153, 51, 255));
        nivelJ.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        nivelJ.setForeground(new java.awt.Color(255, 0, 51));
        nivelJ.setText("DIFICIL");
        getContentPane().add(nivelJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 160, 40));

        ultimoPontos.setFont(new java.awt.Font("Century Gothic", 1, 60)); // NOI18N
        ultimoPontos.setForeground(new java.awt.Color(204, 0, 0));
        ultimoPontos.setText("23");
        getContentPane().add(ultimoPontos, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 100, 160));

        wpp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/memory/resources/Vitoria.png"))); // NOI18N
        getContentPane().add(wpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Menu.setText("jButton1");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, 130, 40));

        jogarNovamente.setText("jButton1");
        jogarNovamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogarNovamenteActionPerformed(evt);
            }
        });
        getContentPane().add(jogarNovamente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 160, 50));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        // TODO add your handling code here:
        MenuDificuldade menuD = new MenuDificuldade(jogador);
        menuD.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuActionPerformed

    private void jogarNovamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogarNovamenteActionPerformed
        // TODO add your handling code here:
        Solo solo = new Solo(jogador,nivel);
        solo.setVisible(true);
    }//GEN-LAST:event_jogarNovamenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VitoriaSolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VitoriaSolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VitoriaSolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VitoriaSolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VitoriaSolo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jogarNovamente;
    private javax.swing.JLabel nivelJ;
    private javax.swing.JLabel recordePontos;
    private javax.swing.JLabel ultimoPontos;
    private javax.swing.JLabel wpp;
    // End of variables declaration//GEN-END:variables
}
