/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.memory.views;

import com.memory.bean.Jogador;
import com.memory.bean.Jogo;
import com.memory.dao.JogadorDAO;

/**
 *
 * @author Caique
 */
public class Vitoriap1 extends javax.swing.JFrame {

    /**
     * Creates new form GameOver
     */
    private Jogador jogador;
    private int acertosp1;
    private int acertosp2;
    private int recs = 0;
    private int nivel = 0;
    public Vitoriap1(Jogador jogador, int acertosp2, int acertosp1) {
        initComponents();
        this.jogador = jogador;
        this.acertosp1 = acertosp1;
        this.acertosp2 = acertosp2;

        alterarRecorde();
        
    }

    public Vitoriap1() {
        initComponents();
    }

    private void conquista() {
        JogadorDAO jogadorD = new JogadorDAO();
        jogadorD.verificarEAdicionarConquista(jogador, 3);
    }

    private void alterarRecorde() {

        ultimoPontos.setText(String.valueOf(acertosp1));
        p2.setText(String.valueOf(acertosp2));
        
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p2 = new javax.swing.JLabel();
        ultimoPontos = new javax.swing.JLabel();
        wpp = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        jovarNovamente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p2.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        p2.setForeground(new java.awt.Color(204, 0, 0));
        p2.setText("23");
        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 100, 160));

        ultimoPontos.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        ultimoPontos.setForeground(new java.awt.Color(204, 0, 0));
        ultimoPontos.setText("23");
        getContentPane().add(ultimoPontos, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 100, 160));

        wpp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/memory/resources/WinP1.png"))); // NOI18N
        getContentPane().add(wpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        voltar.setText("jButton1");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, 130, 40));

        jovarNovamente.setText("jButton1");
        jovarNovamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jovarNovamenteActionPerformed(evt);
            }
        });
        getContentPane().add(jovarNovamente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 150, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(jogador);
        menu.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_voltarActionPerformed

    private void jovarNovamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jovarNovamenteActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(jogador);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jovarNovamenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vitoriap1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vitoriap1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vitoriap1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vitoriap1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vitoriap1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jovarNovamente;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel ultimoPontos;
    private javax.swing.JButton voltar;
    private javax.swing.JLabel wpp;
    // End of variables declaration//GEN-END:variables
}
